[workspace]
resolver = "2"
members = ["circuits/host", "circuits/methods", "circuits/core", "operator"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
