[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.19.1" }
env_logger = "0.10"
serde = "1.0"
hex = "0.4.3"
serde_json = "1.0.108"
sha2 = "0.10.8"
bitcoin = "0.31.0"
