[package]
name = "operator"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { version = "0.31.0", features = ["rand"] }
bitcoincore-rpc = "0.18.0"
hex = "0.4.3"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
sha2 = "=0.10.6"
